### ISSUE TITLE
useGlobal().propertyName does not subscribe to state changes.

### ISSUE THREAD

**Issue by slevy85** [CharlesStover/reactn#100]
Hi,

I have updated from reactn 0.1 to reactn 2, and my component no longer rerenders when I change the global state using `setGlobal`,

Here is a code sample :
```
import React, { setGlobal, useGlobal } from "reactn";

setGlobal({
  count: 0
});

const Root = () => {
  const [global, setGlobal] = useGlobal();
  const { count } = global;
  const increment = () => {
    setGlobal({ count: count + 1 });
  };

  return (
    <div>
      <button onClick={increment}>Increment</button>
      count: {count}
    </div>
  );
};
```
Here is a sandbox :
https://codesandbox.io/embed/naughty-sanderson-de8mp

I tried with reactn 1.0.0 and it works good.

Is it a bug or do I miss something ?

As a side note, when I use `const [count, setCount] = useGlobal('count')` it works good.

Thank you very much.

**Comment by CharlesStover** [comment]
I would recommend using the `useGlobal('count')` for now, but you are right that this should be working. I'll try to reproduce this this weekend and see if it's an actual bug in production.

**Comment by CharlesStover** [comment]
I've investigated this, and it appears to be a bug with CodeSandbox. I'd love for CodeSandbox not to have this bug, but I'm not sure it's within the scope of this project to account for its errors -- or at least it is not priority at this point n time.

[A unit test already existed to verify that `useGlobal().property` subscribes and re-renders correctly.](https://github.com/CharlesStover/reactn/blob/master/tests/use-global/undefined.test.ts#L70)

I validated this functionality in the `docs` directory of this repository with the following codes:

```javascript
// Verify that the Component does re-render when it is subscribed to `color` change.
export default function About() {
  const [ global, setGlobal ] = useGlobal();
  const setColor = () => {
    const hex = '0123456789ABCDEF';
    const randHex1 = Math.floor(Math.random() * 16);
    const randHex2 = Math.floor(Math.random() * 16);
    const randHex3 = Math.floor(Math.random() * 16);
    setGlobal({
      color: `#${hex[randHex1]}${hex[randHex1]}${hex[randHex2]}${hex[randHex2]}${hex[randHex3]}${hex[randHex3]}`
    });
  };
  // should (and does) display the correct color:
  return <button onClick={setColor}>{global.color}</button>;
}
```

```javascript
// Verify that the Component does not re-render when it is not subscribed to `color` change:
let renders = 0;
export default function About() {
  renders++;
  const [ _global, setGlobal ] = useGlobal();
  const setColor = () => {
    const hex = '0123456789ABCDEF';
    const randHex1 = Math.floor(Math.random() * 16);
    const randHex2 = Math.floor(Math.random() * 16);
    const randHex3 = Math.floor(Math.random() * 16);
    setGlobal({
      color: `#${hex[randHex1]}${hex[randHex1]}${hex[randHex2]}${hex[randHex2]}${hex[randHex3]}${hex[randHex3]}`
    });
  };
  // should (and does) remain 1:
  return <button onClick={setColor}>{renders}</button>;
}
```

As a result, I'm going to close this issue as working. Again, I'm not sure why it doesn't work on CodeSandbox, but it doesn't appear to be a problem with the package itself and is likely an integration issue with CodeSandbox.
