### ISSUE TITLE
external React

### ISSUE THREAD

**Issue by mstruensee** [CharlesStover/reactn#101]
How does this work with projects that have React provided on the page as an external?
Does it end up bundling an entire version of react when you change the import to reactn or will reactn use the externalized React?

**Comment by CharlesStover** [comment]
ReactN does not contain any version of React in itself. It attempts to use the React installation in your `node_modules` directory. You can use whatever version of React you want. Whatever is in your `node_modules/react` directory is what will be used. 🙂
