### ISSUE TITLE
feature: persistence 

### ISSUE THREAD

**Issue by morrys** [CharlesStover/reactn#114]
Hi,
I have created a library that allows any object to persist in a simple and efficient way with a remarkable capacity of configuration and extension.

https://github.com/morrys/wora/tree/master/packages/cache-persist

I have already used it to implement persistence in [relay modern store](https://github.com/facebook/relay) with [wora/relay-store](https://github.com/morrys/wora/tree/master/packages/relay-store) and for [apollo cache inmemory](https://github.com/apollographql/apollo-client/tree/master/packages/apollo-cache-inmemory) with [wora/apollo-cache](https://github.com/morrys/wora/tree/master/packages/apollo-cache)

If you are interested in its possible integration (requires few modifications) please contact me on twitter: https://twitter.com/m0rrys

Lorenzo

**Comment by CharlesStover** [comment]
Is this for persisting from the server to the client? Issue #9 deals with that feature.

Or is this for persisting from within the client across sessions?

**Comment by morrys** [comment]
It's the second one you said.

These days I have also created a more detailed library [documentation](https://morrys.github.io/wora/docs/cache-persist)

**Comment by CharlesStover** [comment]
I don't think client-side persistence is a goal to be integrated into this package directly, but I more than welcome extension packages (like [`reactn-devtools`](https://www.npmjs.com/package/reactn-devtools)) which build upon the base functionality. For example, Fooxly has some tools such as [LoggerN](https://www.npmjs.com/package/@fooxly/loggern) and [PersistN](https://gitlab.com/fooxly/persistn). If you would like to make such a package, I am fine with a chunk of documentation that links to and supports these packages.

**Comment by morrys** [comment]
I understand, creating a library is no problem for me. For better integration and to ensure better efficiency, it would be very useful if you could manage the state not directly using an object but an extension such as [relay record source](https://github.com/facebook/relay/blob/master/packages/relay-runtime/store/RelayRecordSourceObjectImpl.js)
or [apollo object cache](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-cache-inmemory/src/objectCache.ts)

This will allow a very simple integration as for the apollo cache in wora/apollo-cache

**Comment by CharlesStover** [comment]
There are no current plans to refactor the global state manager, but I do welcome any libraries. 😄
