### ISSUE TITLE
useGlobal without subscription

### ISSUE THREAD

**Issue by runar-indico** [CharlesStover/reactn#119]
For some components, I only wish to update the state, but not subscribe to updates at all. Is this possible?

**Comment by CharlesStover** [comment]
This was a feature in 1.0 (`useGlobal('property', true)`) but was dropped in 2.0 for being under-demanded, unintuitive, and difficult to maintain in TypeScript. There is not currently a way to do this with `useGlobal('property')`, but you can do it with `useGlobal()`, which does not subscribe unless you access a property.

```typescript
const [, setGlobal] = useGlobal();
// ...
setGlobal({ property: 'new value' });
```

It's not as convenient as `setProperty('new value')`, but it works and makes lexical sense as the property value is not being accessed.

Let me know if this satisfies your use case, or if there is demand for reinstating `useGlobal('property', true)`.
