### ISSUE TITLE
Issue with react native

### ISSUE THREAD

**Issue by Brianop** [CharlesStover/reactn#130]
Im currently using react native 0.60.3, I upgraded from 2.1.6 to 2.2.3 and got this error:

![Captura de Pantalla 2019-09-24 a la(s) 12 47 15](https://user-images.githubusercontent.com/15720472/65536681-84d73580-dec9-11e9-83bb-5134adbe76f3.png)

Has anyone found a solution for this?

_Originally posted by @plouh in https://github.com/CharlesStover/reactn/issues/129#issuecomment-534014008_

**Comment by CharlesStover** [comment]
This was a change in 2.2.3 to optimize rendering in browsers. I'll publish 2.2.4 to revert this change, since it is not supported by React Native.

**Comment by Brianop** [comment]
Thanks @CharlesStover

**Comment by CharlesStover** [comment]
This is pushed. Give it a few minutes, and TravisCI should have it deployed to NPM under `2.2.4`. Thanks for the report.
