### ISSUE TITLE
Question: Correct way to set values from promise calls

### ISSUE THREAD

**Issue by groundswel** [CharlesStover/reactn#140]
Thank you so much for writing ReactN. Now I at least have some hope of writing a React application. However I saw some behavior that I cannot understand and hoping to get some explanation . It’s probably newbie question but I have been struggling now for some time. So I created a typical react app with App.js where App is a react component. I use setGlobal to set up the global object which contains {usergroups:[], currentgroup:’’}. Now in one of the components (say Home) I call a function ie setusergroups (which is imported from another file) to set up usergroups and currentgroup. If I hardcore currentgroup it correctly updates the global state. But usergroups is a result of a promise function that returns somevalue on which I have to do some further operations and then I am trying to call setGlobal to update usergroups. However when  I try to do a getGlobal.usergroups it is always undefined in the App or Home component. Even after the components are rendered it is undefined. But getGlobal.currentgroup returns correct value. What is the correct way to set usergroups or other variables in the global state that will be the result of promise or async calls? Why is getGlobal.usergroups in App and Home undefined but shows the desired value inside the setusergroups function? 

TIA

**Comment by CharlesStover** [comment]
Can you share your existing code that is not working? It would be easier to point out the problematic area and the correct alternative.

There are two ways to update state based on a Promise:

1. Execute the Promise, _then_ update the state.
2. Pass a Promise that returns the new state.

For 1, you would do something like this:
```
fetchUserGroups()
  .then(userGroups => {
    setGlobal({ userGroups });
  });
```

For 2, it would look something like this:
```
setGlobal(
  fetchUserGroups()
    .then(userGroups => ({ userGroups })),
);
```

Both will do the same thing, so it's really a matter of preference for what makes the most sense to you.

**Comment by groundswel** [comment]
Thanks for your response. I have tried to share the code sample through https://stackblitz.com/edit/react-7cg5kd

As you can see the App.js constructor calls the function GetUserCogGroups function to set the global state. While current_group is set correctly , uaergroups which is a result of the promise action is not set correctly.

**Comment by CharlesStover** [comment]
This stackblitz does not show output, but just going by the code, the issue is likely that you need to replace `getGlobal()` with `this.global`. `getGlobal` exists explicitly to _not subscribe to state changes_. You are likely seeing your initial state, but since the component does not subscribe to state changes, you do not get updates to that state when those properties change.

* `this.global.current_group` will subscribe to `current_group` changes.
* `getGlobal().current_group` will not subscribe to `current_group` changes, and will only show you the value of `current_group` at time of render and not future values.
