### ISSUE TITLE
useGlobal triggering networking  calls continuously 

### ISSUE THREAD

**Issue by groundswel** [CharlesStover/reactn#144]
Hi 

I am using useGlobal in a functional component. The functional component calls another function to make the promise call to update the global state via setState. The functional component also renders some content with values fetched from the global state. While it seems to run properly and fetches the correct value , from the console log I can see it is continuously triggering the remote call and making network requests. Is there a way to tell useGlobal to refresh only when the global state is updated and not to keep making calls continuously ? What is the correct approach to use useGlobal in such scenario?

Thanks

**Comment by umbertoghio** [comment]
Hi, 
are you sure the side effect of your network request includes updating the global state which triggers a re-render which triggers another side effect and subsequent network request.......

I would do the fetching in the parent component and once ready render the child

**Comment by groundswel** [comment]
Thank you @umbertoghio .. that was it!! I was expecting that when useGlobal update the global state then React or ReactN will  only update the JSX part of the components where the useGlobal properties are used. But it is actually the whole component that re-runs when re-rendering. Not sure if my understanding is correct but looks like I need to think in terms of seperating functional components (ie that will have business logic and call functions etc) and presentational components.  Just not sure how far I can stretch this specially with the highly interactive parts of the application.
