### ISSUE TITLE
Is the project still maintained ?

### ISSUE THREAD

**Issue by ASHFAQPATWARI** [CharlesStover/reactn#145]
@CharlesStover  I have been using this library but now I don't see any activity happening. Would like to know if this project is still active.

**Comment by CharlesStover** [comment]
I've been swamped with work priorities, unfortunately; so personal projects have taken a back seat. I like to think of it as in a healthy state for the time being, as open bugs are typically edge case TypeScript typings. I'll be doing a bit of maintenance at the moment; I've just merged in the pull request to remove console warnings in developer mode with class components. :)

For the time being, new features or other improvements will likely need to be community-driven. I am more than welcoming to PRs.
