### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by MohamadKh75** [CharlesStover/reactn#149]
Hey

Thanks for all the effort :heart: 

I wonder where can I track changes (since there is no new tag in [releases ](https://github.com/CharlesStover/reactn/releases) from 2.2.0).

Is that intentional? Or I should create a PR?

**Comment by CharlesStover** [comment]
Releases is where I intended to track each change. Sometimes it just skipped my mind. 😬

I'll add some new ones.
