### ISSUE TITLE
How to spy on "global" in class component

### ISSUE THREAD

**Issue by darrensw777** [CharlesStover/reactn#154]
In my class component, I have a viewData object set globally which I access using:

**this.global.viewData**

All works as it should.

Now I want to test the component but when trying to spy on the global method I get the error

> Cannot spy the global property because it is not a function; undefined given instead

This is how I'm setting up the spy:

`wrapper = shallow(<Payment />);
    const setGlobalSpy = jest.spyOn(wrapper, 'global').mockImplementation(() => {
        return { viewData };
    });`

Is there a better way for me to mock this?

**Comment by CharlesStover** [comment]
Thanks for supporting the project, and thanks for writing tests for your code!

This error is accurate. `global` is not a function per se; it is a _getter_ method. Depending on your version of Jest, the syntax for this may be different.

I believe the most common syntax for this is to use `jest.spyOn(wrapper, 'global', 'get')` (just add the third parameter). If this doesn't work, look up spying on "getter" methods in Jest for your chosen version. 🙂
