### ISSUE TITLE
Can we drop in preact in place of React while using Reactn?

### ISSUE THREAD

**Issue by bvjebin** [CharlesStover/reactn#161]
I tried with what `preact` doc said using `preact/compat` as alias for react in `webpack` config. It broke the whole application.

Global state update was causing the application to break.

```
function ReactNGlobalCallback(that) {
    that.updater.enqueueForceUpdate(that, null, 'forceUpdate');
}
```
`enqueueForceUpdate of undefined` is the error

Preact provides bundle size reduction in production. The benefit is a considerable win.

**Comment by CharlesStover** [comment]
This code branch may only be used by class components. If that's the case, you may be able to use Preact so long as you only use function components. If, however, this branch is used by function components, there is no workaround to my knowledge. `that.updater/enqueueForceUpdate` is a core functionality requirement that allows ReactN to re-render a component when the global state has changed. You may want to contact the Preact team to ask what the equivalent is for their product.
