### ISSUE TITLE
why is useEffect exported from the package?

### ISSUE THREAD

**Issue by pke** [CharlesStover/reactn#170]
The auto import in VSCode always adds the import from "reactn" instead of "react-native" when I type `useEffect`

So I wonder how does the reactn useEffect differ from the original?

**Comment by CharlesStover** [comment]
It's the exact same function, even down to it's location in memory. The intention of reactn was to be able to replace all instances of react and still function the same a react with the addition of global state. This isn't as noticeable now that hooks are a thing, but ReactN was made before hooks, and this was particularly relevant when working with class components, which needed additional global methods.

I don't know how to teach an IDE which function to import, unfortunately.

**Comment by pke** [comment]
thanks Charles for the explanation!  Didn't catch your reply earlier.
