### ISSUE TITLE
react native compatible?

### ISSUE THREAD

**Issue by ddikodroid** [CharlesStover/reactn#178]
can i use this package in react native project?

**Comment by CharlesStover** [comment]
Yes, you can. :)

**Comment by JegoYann** [comment]
Hello ! I do use ReactN with React Native and it works nicely. Except for the re-rendering after a `this.setGlobal()`. React Native and Expo now implements React Hook (https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c#7cec).

Any idea why ReactN does not trigger components re-rendering ?

**Comment by CharlesStover** [comment]
If you are not wrapping your app in the ReactNProvider, you may also try that.

Otherwise, I'm not sure why it would not work. ReactN supports React Native, but it's not a RN-first approach. If you have the option to use hooks, I'd suggest using them where possible.

**Comment by JegoYann** [comment]
I don't see any doc about `ReactNProvider`. Could you provide a little exemple to see how to import and use it ?

**Comment by JegoYann** [comment]
Hi again @CharlesStover !
I create a small example to reproduce the issue. Would it help you to find a fix ?
