### ISSUE TITLE
is it work in react native

### ISSUE THREAD

**Issue by Q8hma** [CharlesStover/reactn#19]
Hello
I want to ask if it work or support react native ??
and if not work there are any way to make it ?
thanks

**Comment by CharlesStover** [comment]
It should. If you have any problems getting it to work, open a specific issue, and I'll try to resolve it ASAP.

**Comment by rotoxl** [comment]
I've made a small test and a red-screen appeared saying `React v16.7 or newer is required for useGlobal`. I know this is not directly related with the library but the default `package.json` that comes bundled in with a new RN project (2018-12-5) is:

```
{
  "name": "last_fm_circle_ci",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.1",
    "react-native": "0.57.7",
    "reactn": "^0.1.6"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.50.0",
    "react-test-renderer": "16.6.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

So, I guess, time to use ReacN on our ReactNative projects has to wait for ReactNative to catch up.

**Comment by CharlesStover** [comment]
React Native doesn't support React 16.7 to my knowledge yet, so you can't use hooks such as `useGlobal`. The rest of ReactN should work! Check out the README for this repo to see examples of ReactN class components using `this.global` and `this.setGlobal`, as well as the `withGlobal` higher-order component.
