### ISSUE TITLE
Document how to put arrays and etc. in global state

### ISSUE THREAD

**Issue by LoganDark** [CharlesStover/reactn#201]
I'm currently unsure how to deal with mutable objects in global state. Do you just do `global.push(...); setGlobal(global)`? Would be helpful to have some documentation on this.

**Comment by CharlesStover** [comment]
Good question. You should be treating your global state as if it is _immutable_, even if it is mutable. Making a change to a mutable global state object _will not trigger a re-render_. Typically, you want mutations to trigger a re-render. As a best practice, it's easiest to assume your global state object is immutable at all times.

Let me know if you have any more questions.

**Comment by LoganDark** [comment]
> Let me know if you have any more questions.

How _do_ I trigger a re-render when modifying global state? Can I just set a property to itself?

**Comment by CharlesStover** [comment]
The call to `setGlobal` is what triggers the re-render. :)

**Comment by LoganDark** [comment]
> The call to `setGlobal` is what triggers the re-render. :)

Good to know, thank you! Leaving this issue open because this is a common use-case that doesn't seem to have any best practices listed

**Comment by monteiz** [comment]
This is not an issue and should be closed. Nowhere in the documentation there is any `global.push` line, while it is obvious that you should interact with the global object only through the dedicated methods.

**Comment by LoganDark** [comment]
> This is not an issue and should be closed. Nowhere in the documentation there is any `global.push` line, while it is obvious that you should interact with the global object only through the dedicated methods.

Unnecessary hostility.

For future reference, the way to update arrays is global state is to call `setGlobal` with a new object, to push to arrays it's `[...oldArray, newObject]`. To remove `filter` can be used, and so on.
