### ISSUE TITLE
Autocompletion

### ISSUE THREAD

**Issue by pungggi** [CharlesStover/reactn#31]
Hi, is there a way to get autocompletion of my store? 

I am doing>
```ts
interface Store {
  fahrenheit: number
}

export const store: Store = {
  fahrenheit: 79
}
...
setGlobal(store)
```

then 
```js
import React, { useGlobal } from "reactn"

export default () => {
  const [store, updateStore] = useGlobal()
  const onColder = () => {
    updateStore({ fahrenheit: store.fahrenheit - 1 })
  }
...
```

I was expecting by typing `store.`  the autompletion would kick in..

Migrating from https://github.com/gunn/pure-store/blob/master/src/index.ts 
where this works great.

**Comment by CharlesStover** [comment]
I haven't tried it without specifiying a property, but `useGlobal<Store>()` may be what you're looking for. I have used this as `useGlobal<number[]>('ids')` to retrieve a list of numbers for example. If it doesn't work for the entire global state, let me know, and I'll implement. In the meantime, if you want to use `useGlobal<number>('fahrenheit')`, I know for fact that it works.

`updateFahrenheit(f => f - 1)`
