### ISSUE TITLE
Error: React v16.7 or newer is required.

### ISSUE THREAD

**Issue by Mindgames** [CharlesStover/reactn#34]
**Error: React v16.7 or newer is required**
`at t.exports  /reactn/index.js:1:12795`

**Issue occured after updating**
`^16.7.0-alpha.0` > `^16.7.0`

**Tested**
- Removing / Installing `node_packages`  = 👎
- Removing yarn lock file   = 👎 
- Downgrading  to '16.7.0-alpha.0'  = 👎 

So now am confused what the cause of this issue could be. Could be something locally for me even if i did multiple modules wipe / install runs.

**Comment by CharlesStover** [comment]
You should only see this error when trying to use hooks in a version if React that doesn't support them.

[16.7.0 (non-alpha) does not support hooks.](https://reactjs.org/blog/2018/12/19/react-v-16-7.html#can-i-use-hooks-yet)

You are still free to use the class syntax (examples in the ReactN README) to access global state or the higher order component to convert global state to props.

Unfortunately, upgrading from alpha to non-alpha removed the built in React hook system from your installation.

The error maybe could be adjusted to make more sense now, since technically 16.7 isn't the criteria for hooks.

**Comment by CharlesStover** [comment]
Let me know if you still have an issue. Closing this for now, as I received a DM on Twitter with a similar problem who said it was resolved by downgrading back to alpha.

**Comment by omrumbakitemiz** [comment]
I haven't deleted the Node_modules folder for a long time. I deleted it today. And installed dependencies with yarn install. But I got this error. I have a copy of the project's node_modules folder not deleted and it works. The codes are exactly the same when i look git status. However, I get the same error when I delete the node_modules folder and do the yarn install. This is so interesting.

Here is my configurations:
_"react": "^16.7.0-alpha.0",
"react-dom": "^16.7.0-alpha.0",
"react-scripts": "2.1.1",
"reactn": "^0.1.6"_

**Comment by CharlesStover** [comment]
Can you confirm the version number is React by checking node_modules/react/package.json?

That error occurs when you use hooks in a version that doesn't support it. Counterintuitively, 16.7 non-alpha doesn't support hooks.

**Comment by omrumbakitemiz** [comment]
> Can you confirm the version number of React by checking `node_modules/react/package.json`?
> 
> That error occurs when you use hooks in a version that doesn't support it. Counterintuitively, 16.7 non-alpha doesn't support hooks.

* React version 16.7.0 in "node_modules/react/package.json" 
<img width="385" alt="screen shot 2019-01-02 at 19 33 42" src="https://user-images.githubusercontent.com/12871066/50601491-5d68b480-0ec5-11e9-9ab7-b57b0f677ddb.png">



* But in my project's package.json  react version is 16.7.0-alpha.0
<img width="229" alt="screen shot 2019-01-02 at 19 36 15" src="https://user-images.githubusercontent.com/12871066/50601609-b9cbd400-0ec5-11e9-8075-0ea76f263016.png">

Am i doing wrong configuration or missing something?

**Comment by CharlesStover** [comment]
Facebook just did something weird with their React versioning by removing hooks from 16.7 despite them being in alpha. Take the `^` off your version number and try installing again.

**Comment by omrumbakitemiz** [comment]
I removed `^` and all problems are solved. Thank you very much. 🎉

**Comment by kesteinbakk** [comment]
Should the documentation in readme.md under "Functional Components" be updated? Currently it says: "Using React Hooks in React v16.7, you can harness useGlobal to access the global state." This is now a bit misleading and should probably just refer to "future versions" and/or linking [here](https://reactjs.org/blog/2018/12/19/react-v-16-7.html#can-i-use-hooks-yet). (And probably with some bold text or something as I completely missed this part when I first read the docs and got the above error)

**Comment by CharlesStover** [comment]
I agree the error is incorrect. I will update the error thrown and the documentation now.
