### ISSUE TITLE
Prevent forceUpdate on components without a render method

### ISSUE THREAD

**Issue by syron0** [CharlesStover/reactn#36]
Hi @CharlesStover, thanks for your great work.
I think it could be useful to prevent `forceUpdate` invocation on Components that doesn't have a `render` method.
Something like this seems to be enough:
```
function ReactNGlobalCallback(_this) {
	if (typeof _this['render'] === 'function') {
		_this.updater.enqueueForceUpdate(_this, null, 'forceUpdate');
	}
}
```
Nevertheless, I suppose there's a better way to handle this situation, provided that it makes sense to you.

**Comment by CharlesStover** [comment]
Do you have any React documentation discussing components without render methods? This is the first I'd heard of them. I've always been under the impression that the standard for a component that doesn't render anything would be to have a render method that returns null.

**Comment by syron0** [comment]
I think you're perfectly right and I agree with you.

However, I came to this conclusion as I'd like to separate app layers, while using reactn.
Given the fact that I can't access `this.global` in a functional component (excluding Hooks usage, of course), my current understanding, correct me if I'm wrong, brings me to think that the only way to go is to create a class that extends Component for the solely purpose of accessing the global object.

In my case it can be useful to create a service layer while being able to access `this.global` inside of its methods. In this case, said component will not be mounted, instead it will be istantiated programmatically.

Another use case may be registering functions on the global object and, as in the previous example, access `this.global` inside of them. If I do it inside a certain component, a double updating cycle may occur. The effect is more severe if we're talking about a first level component, e.g. "App". For that reason, I'd like to separate them too.

I perfectly know that I could just pass as arguments the global items that I want to access inside these methods in order to avoid this behaviour, but for the sake of simplicity I thought it could be useful to have said possibility.

**Comment by CharlesStover** [comment]
I'd test this myself but I'm on vacation without a computer. What happens if you make a React (not ReactN) component without a render method and call forceUpdate, e.g. in a setTimeout in componentDidMount? Does it throw an error? IMO, ReactN should mimic React's behavior for a component without a render method.

**Comment by syron0** [comment]
You're right, it mimics React's behaviour by throwing an error while mounting, because it can't find the render method, but of course this happens if I try to render it.
Actually, my issue wasn't related to that.

Let's say I create a "service"; this would normally be just a functional component but, in order to access `this.global.x`, this service must extends Component.
Of course there's no need to mount and render it (by referencing it in another Component's `render()`), I just have to instantiate it programmatically with `new Service()`.
However, ReactN will "register" the service's access to the global variable and proceed to forceUpdate it once it changes. This will result in a warning:

> Warning: Can't call forceUpdate on a component that is not yet mounted. [...]

I thought it could be useful to handle this situation and avoid the forceUpdate() call.

**Comment by CharlesStover** [comment]
I'll let this ruminate in my head for a bit before making any swift decisions.

Part of me thinks you should just have a render method that returns null for a service component. You are still extending a React Component, and the behavior should match React's behavior, which requires a render method.

Is there a reason to avoid `render() { return null; }`?

**Comment by syron0** [comment]
The reason is that a service class would be instantiated programmatically, so it wouldn't be mounted and rendered like a standard React component, it just has to extend it in order to access `this.global`.
In this case, the Component will not be mounted nor rendered, and having or not a render method would be irrelevant.

**Comment by CharlesStover** [comment]
Does your service class respond to global state changes with componentDidUpdate?

What would the undesired side effects be to having <Service /> (with render null) in your App (or whatever is calling new Service) component's render method?

**Comment by syron0** [comment]
> Does your service class respond to global state changes with componentDidUpdate?

No, `componentDidUpdate` is never called because the service isn't mounted and rendered, it's instantiated with the `new` keyword. By doing so, this service will not follow a standard React Component's lifecycle. Said service will not be mounted, but reactn will register its access to `global` and try to call `forceUpdate()` on it, resulting in the aforementioned warning:

> Warning: Can't call forceUpdate on a component that is not yet mounted. [...]

I'd like to just avoid this call.


> What would the undesired side effects be to having (with render null) in your App (or whatever is calling new Service) component's render method?

I'm sorry but I'm not sure I completely understood this question, could you please re-elaborate it?

**Comment by CharlesStover** [comment]
So you're just trying to access a global state snapshot outside of a component and not subscribe to updates? Would something like `getGlobal()` that returns a snapshot of the state as it currently exists better suit your needs? See #36.

**Comment by syron0** [comment]
> Would something like getGlobal() that returns a snapshot of the state as it currently exists better suit your needs?

I suppose you meant to reference #35.
Anyway, it would surely do, that would be more than useful!

> Is there a reason not to do this:

I wanted to avoid referencing what should be a functional component inside a render method for the solely purpose of "mounting" it and not to generate the mentioned warning.
In addition to that, I think that this solution may hinder any dependency injection (or sort of) architecture.

**Comment by CharlesStover** [comment]
If #35 suits your need, I will close this in favor of that issue.
