### ISSUE TITLE
Global Providers should have hooks as static methods (Provider.useGlobal)

### ISSUE THREAD

**Issue by ralphievolt** [CharlesStover/reactn#37]
Current is 
`setGlobal({
  cards: [],
  disabled: false,
  initial: 'values',
  x: 1
});
`

Is it possible to group these global state like the following for better control and code management?

`setGlobal-A({
  cards: [],
  disabled: false,
  initial: 'values',
  x: 1
});
`

and

`setGlobal-B({
  posts: [],
  blogger: 5
});
`

**Comment by CharlesStover** [comment]
I'm not sure I understand what the difference between A and B are. Can you elaborate?

**Comment by bhgsbatista** [comment]
`Provider1.useGlobal('cards')` seems like a hook friendly version of React context. It seems much more natural to me.
