### ISSUE TITLE
Feedback after reading 'No-boilerplate global state management in React'

### ISSUE THREAD

**Issue by EECOLOR** [CharlesStover/reactn#39]
Hi there,

thanks for writing the great article and turning your thoughts into a library.

What I would like to see from a global state library is the following light-weight version:

**Setting up global state**
```jsx
import { GlobalStateProvider } from 'reactn'

export default function MyRoot() {
  return (
    <GlobalStateProvider initialState={...} ...>...</GlobalStateProvider>
  )
}
```

**Using the global state**
```jsx
import { useGlobal } from 'reactn'

export default function MyComponent() {
  const [x, setX] = useGlobal('y.x')
  const [globalState, setGlobalState] = useGlobal()
}
```

You could add support for `reducers` and `callbacks` on the `GlobalStateProvider`.

I understand that you would like to support the component world as well, but I recommend to put that into another package (or put this into `reactn-light`).

I hope this feedback helps you.

**Comment by EECOLOR** [comment]
Oh, and feel free to close this issue.

**Comment by CharlesStover** [comment]
The Provider is currently the highest priority feature, as it's needed for concurrent server-side rendering. Whenever concurrent SSR is supported, I'll cut `1.0.0` of the package.

`useGlobal` as a hook works as you have it now, except I'm still very on the fence about nested values. I love them in concept, but it's about the performance ramifications of implementing them. Currently, you'd have to use `useGlobal('y')`.

`useGlobal()` does return the entire global state and a setter for it.

I will separate component logic and hook logic when React's main package does the same (presumably deprecated components).

The day React deprecates components, I'll cut a release of ReactN that is hooks-only.
