### ISSUE TITLE
useGlobal should match useReducer when passed a function

### ISSUE THREAD

**Issue by WilliamTheMarsman** [CharlesStover/reactn#42]
Following the classic example presented in this article, but with typescript:

https://gist.githubusercontent.com/CharlesStover/285f95bba12cd9468276d766a87a3568/raw/c386149729ff7d17c16318563be6613baf933448/global-reducer.js

I am playing a little fast and loose with types here. I am unsure what to do with the `LocalReducer` type returned in this scenario.

## Expected

`useGlobal(reducer)` returns types compatiable with `[state, dispatch]`

## Actual

`useGlobal(reducer)` returns `LocalReducer`

### Code

```
import { useGlobal } from "reactn";

const initialState = { count: 0 };
function reducer(state: any, action: { type: string }) {
  switch (action.type) {
    case "reset":
      return initialState;
    case "add":
      return { count: state.count + 1 };
    case "subtract":
      return { count: state.count - +1 };
    default:
      return state;
  }
}

function Counter({ initialCount = 0 }) {
  const [state, dispatch] = useGlobal(reducer);
  return (
    <>
      Count: {state.count}
      {/* and can dispatch certain events here */}
      <button onClick={() => dispatch({ type: "reset" })}>Reset</button>
      <button onClick={() => dispatch({ type: "increment" })}>+</button>
      <button onClick={() => dispatch({ type: "decrement" })}>-</button>
    </>
  );
}
```

### Error

```
Type 'LocalReducer' is not an array type.ts(2461)
const dispatch: any
```

**Comment by CharlesStover** [comment]
Great report! I think the TypeScript definition doesn't consider reducers. I'll definitely look into this.

**Comment by WilliamTheMarsman** [comment]
Thanks, that clears it up for me. It would probably be easier for others if it matched React, but I will be using the mechanism you've proposed for now.

Thanks for your work on this project!

**Comment by CharlesStover** [comment]
I may be able to do both by adding a `[Symbol.iterator]` property to the returned dispatch function, such that [0] is the full global state and [1] is the same dispatch function.

Needs testing.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols

**Comment by WilliamTheMarsman** [comment]
I made a working version of this as well. This is all being done in a `create-react-app --typescript` project, where I've simply inlined 3 counters to verify its working. 

```
import React, { Component } from "react";
import { useGlobal } from "reactn";

// State appears to be all global state
const initialState = { count: 0 };
function reducer(state: any, action: { type: string }) {
  switch (action.type) {
    case "reset":
      return { counter: { count: initialState } };
    case "increment":
      return { counter: { count: state.counter.count + 1 } };
    case "decrement":
      return { counter: { count: state.counter.count - +1 } };
    default:
      return state;
  }
}

export function Counter() {
  const [state]: any = useGlobal("counter");
  const dispatch = useGlobal(reducer);
  return (
    <>
      Count: {state.count}
      {/* and can dispatch certain events here */}
      <button onClick={() => dispatch({ type: "reset" })}>Reset</button>
      <button onClick={() => dispatch({ type: "increment" })}>+</button>
      <button onClick={() => dispatch({ type: "decrement" })}>-</button>
    </>
  );
}
```

Right now the reducer receives the entire global state on dispatch. In React, we specify the initial state as the second argument into the `useReducer` method, like so: 

```
const [state, dispatch] = useReducer(reducer, { count: initialCount });
```

This isn't necessary when working with global state, since globals are initialized elsewhere. But would it make sense to specify the global state the reducer should subscribe to? I've included an example of what this would look like below.

```
import { setGlobal } from "reactn";
// In GlobalState.ts
setGlobal({
  avatar: "anonymous.png",
  counter: { count: 0 }
});

// In index.tsx
...
import "./GlobalState";

ReactDOM.render(<App />, document.getElementById("root"));
...

// in Counter.tsx
import React, { Component } from "react";
import { useGlobal } from "reactn";

// State appears to be all global state
const initialState = { count: 0 };
function reducer(state: any, action: { type: string }) {
  switch (action.type) {
    case "reset":
      return { count: initialState };
    case "increment":
      return { count: state.counter.count + 1 };
    case "decrement":
      return { count: state.counter.count - +1 } };
    default:
      return state;
  }
}

export function Counter() {
  const [state, dispatch] = useGlobal(reducer, "counter");
  return (
    <>
      Count: {state.count}
      {/* dispatch only on state.counter */}
      <button onClick={() => dispatch({ type: "reset" })}>Reset</button>
      <button onClick={() => dispatch({ type: "increment" })}>+</button>
      <button onClick={() => dispatch({ type: "decrement" })}>-</button>
    </>
  );
}
```

This way, global reducers can subscribe only specific global state.

**Comment by CharlesStover** [comment]
There's no need for the subscription property list, because your component will subscribe any time you _access_ that property. So where you are displaying `Count: {state.count}` is causing a subscription on count. If your view is dependent on a property, it will be subscribed to that property auto-magically.

I believe I have the iteration property working so that both `const dispatch = useGlobal(reducer)` and `const [ state, dispatch ] = useGlobal(reducer)` work. It is passing unit tests, but I worry about cross-browser compatibility.

I'll do some manual testing to make sure current apps reliant on ReactN won't break with this change. If not, I'll ship this feature in 1.0 this weekend.
