### ISSUE TITLE
Would it be possible to pull this apart into just a hook and hoc?

### ISSUE THREAD

**Issue by Bored0ne** [CharlesStover/reactn#44]
I have a hard time wanting to replace react's general implementation but I wouldn't mind importing an extension when I need it ie run a setup function in the App.js and whenever I need access to global state I add a hoc or hook to pass it to me.

**Comment by CharlesStover** [comment]
I'm not sure what you mean. ReactN does not replace React's general implementation. If you only want to use the hooks and HOC, do the following:

```JavaScript
import React from 'react';
import { useGlobal, withGlobal } from 'reactn';

class NonGlobalComponent extends React.Component {
  render() {
    return `this.global is undefined ${this.global}`;
  }
}

class HocGlobalComponent extends React.Component {
  render `The HOC gives me global access: ${this.global.x}`;
}

const GlobalComponent = withGlobal(HocGlobalComponent);

function GlobalFunctionalComponent() {
  const [ x, setX ] = useGlobal('x');
  return `I am global: ${x}`;
}
```

Hope this makes sense. ReactN components only have global when you import the React namespace from the `reactn` package. ReactN _does not mutate_ the `react` namespace. `reactn` imports `react`, extends it (non-mutating), and re-exports it with global functionality. You can use both `react` and `reactn` simultaneously in the same project.

You are more than welcome to use only the HOC and hooks of `reactn` withotu using `reactn`'s `React` namespace.

If this doesn't address your concern, let me know. :)
