### ISSUE TITLE
Quick question about "How do components update?" in FAQs

### ISSUE THREAD

**Issue by fergusmeiklejohn** [CharlesStover/reactn#45]
If I store an array of objects in Global state, and map over it to render each object in a list with keys. Does ReactN trigger re-render of the entire list of components if I append a new object to the list or change one of the objects?

**Comment by umbertoghio** [comment]
Hi, 
as I understood global state it works the same way as a component state, so you can’t append or edit it in any way.
You must replace the current array with another array that has an additional element, if you have a list using it it will re-render.

Ex 

Const { array: oldArray } = this.global
this.setGlobal({array:[...oldArray, newValue]})

**Comment by CharlesStover** [comment]
>If I store an array of objects in Global state, and map over it to render each object in a list with keys. Does ReactN trigger re-render of the entire list of components if I append a new object to the list or change one of the objects?

Yes, ReactN uses _shallow_ comparison. If `globalState.a.b.c` updates, then Components using `globalState.a.y.z` will re-render, because `globalState.a` updated.

>as I understood global state it works the same way as a component state, so you can’t append or edit it in any way. You must replace the current array with another array that has an additional element, if you have a list using it it will re-render.

This is all true. It is meant to behave as similarly to local state as possible.
