### ISSUE TITLE
Document setGlobal's state merging behavior.

### ISSUE THREAD

**Issue by samsch** [CharlesStover/reactn#52]
One thing I noticed is missing from the documentation is what the merging behavior of setGlobal is.

Does having a state of `{ foo: 'fooVal' }` and doing `setGlobal({ bar: 'barVal' })` get you `{ foo: 'fooVal', bar: 'barVal' }` (what I'm guessing, since that would match how component state works), or `{ bar: 'barVal' }` (the more obvious JavaScript answer).

It would also be helpful to have API docs for the setGlobal and hook setters functions, outlining the possible argument types and the exact behavior for each.

**Comment by samsch** [comment]
This wasn't really fixed. I'd suggest something like adding after this line:
> The first parameter is the new global state that you want to set.

"The properties in the parameter are merged into the global state."

**Comment by CharlesStover** [comment]
It was closed as a `wontfix` moreso than a completed, but I've used your suggestion and added the recommended change. :)
