### ISSUE TITLE
Parent component not updating when using global state from child

### ISSUE THREAD

**Issue by jeghedderchristoffer** [CharlesStover/reactn#53]
I have made i simple reconstruction of what the problem is: 

```
import React, {useState, useGlobal, setGlobal} from 'reactn';
import { render } from 'react-dom';

setGlobal({
  user: {},
});

function Child({ parentFunction }) {
  const [user, setUserData] = useGlobal('user');

  function populateUserObject() {
    // Set user data
    setUserData({
      name: "John doe",
      email: "john@doe.com",
      phone: "29636063",
    });

    // Call parentFunction()
    parentFunction();
  }

  return (
    <div>
      <button onClick={populateUserObject}>Click me to populate global user object</button>
    </div>
  )
}

function Parent() {
  const [user, setUserData] = useGlobal('user');

  function parentFunction() {
    // It should output the user object, but it outputs the initial state!!
    console.log(user);
  }

  return (
    <div>
      <Child parentFunction={parentFunction} />
    </div>
  )
}

render(
  <Parent />,
  document.getElementById('test-reactn')
);
```

When clicking on the childs button, i would expect it to update the global state, and therefor output the user object with data when clicking the button.

The problem is, that it does not do that and returns the initial state, which is an empty object. Clicking the button again, the user object with data is now outputted. 

Am i missing something or is this the expected behavior? 

It is also worth mentioning, that i get the expected behavior, when using class components instead of functional!

**Comment by CharlesStover** [comment]
I think the issue is that re-renders are a set, not a queue, so whether or not the Parent or Child re-renders first is up in the air. I definitely want it to align with React vanilla components, so I will refactor this to match the behavior of class components. I'll try to get a unit test for this use case specifically in the 2.0 milestone to ensure this problem is fixed and matches React's behavior.
