### ISSUE TITLE
Document using ReactN with async/await syntax.

### ISSUE THREAD

**Issue by chadams** [CharlesStover/reactn#63]
Is there an example of using as action with async/await? For example making an API call and then updating state?

**Comment by CharlesStover** [comment]
Setting the state, either via `setGlobal` or dispatching an action directly, is always a Promise in ReactN. Returning a Promise from a reducer or passing a Promise to `setGlobal` will always evaluate the Promise first before setting the state.

Ultimately, ReactN is very Promise-friendly, and however you want to use Promises or async/await is _probably_ correct.

```JavaScript
addReduce('getUsers', async () => {
  const users = await fetch('/api/users');
  return {
    users: await users.json(),
  };
});
// ...
// If the users haven't been fetched yet, fetch them.
if (this.global.users === null) {
  // The reducer itself is also a Promise:
  await this.global.getUsers();
  alert('Users are now set.');
}
```

Let me know if you have a more specific example you want to work with.
