### ISSUE TITLE
Add Fooxly packages to Documentation

### ISSUE THREAD

**Issue by CharlesStover** [CharlesStover/reactn#69]
1) Verify support for 2.0.
2) Add the three packages that exist at: https://www.npmjs.com/package/@fooxly/loggern

**Comment by bpas247** [comment]
I created a CodeSandbox example to verify that this package works for 2.0, although I can't seem to get it to properly log the state changes.

https://codesandbox.io/s/reactn200withloggernexample-lpp8y

Maybe it's not yet supported?

**Comment by LucHermkens** [comment]
@bpas247 I have updated LoggerN to support the newest version of ReactN a few days ago. I still have to write some tests but after that I'll put it live. You can check out development at: https://gitlab.com/fooxly/loggern

**Comment by CharlesStover** [comment]
I welcome this as a PR, but will close the issue for now for cleaning purposes.
