### ISSUE TITLE
Move Redux DevTools to a separate package.

### ISSUE THREAD

**Issue by ryanvanderpol** [CharlesStover/reactn#71]
Just updated to 2.0.0 (yay!) but I'm getting build warnings in my create-react-app-based build scripts:

```
Compiled with warnings.

./node_modules/reactn/build/utils/redux-dev-tools.js
Module not found: Can't resolve 'redux' in '/Users/.../my-project/node_modules/reactn/build/utils'
```

**Comment by CharlesStover** [comment]
Thanks for bringing this up.

Does it still compile successfully? Redux is _optional_ (only used for Redux DevTools). ReactN should work without it.

I am open to cleaner warnings, as this may imply something went wrong, when in fact nothing did.

I want to verify this is just a warning with a functional end result as opposed to an error preventing you from building successfully.

**Comment by ryanvanderpol** [comment]
Yeah, it's just a warning, everything functions properly as far as I can tell, so this isn't a dire situation, but I like to keep my warnings to zero and right now this is the only thing preventing that.  More of an annoyance than an issue, for the moment.

**Comment by CharlesStover** [comment]
I absolutely agree with desiring 0 warnings! It's on the roadmap for 2.0.1.

**Comment by CharlesStover** [comment]
It looks like Webpack refuses to _not_ throw this warning and is perfectly aware that it appears on _all_ _optional_ dependencies.

As a result, I think the best option is to move the Redux DevTools support out of ReactN's base package and into a different package, as some sort of callback or middleware.

I'm going to deploy 2.0.1 today to resolve #73, so I'm punting this to 2.0.2. It is my top priority fix, but I want to make sure it is solved correctly and not rushed today. I'll try to have it deployed before this weekend.

**Comment by CharlesStover** [comment]
Sorry for the delay. This should be done now -- or as soon as Travis CI deploys it to NPM.
