### ISSUE TITLE
Promises returned from the setGlobal helper function

### ISSUE THREAD

**Issue by aarjae** [CharlesStover/reactn#72]
I realize the setGlobal function is an asynchronous function. Is it okay for us to place its usage in an IIFE and if so, update the docs to reflect the use accordingly?
Eg.
```
(async function() {
	await setGlobal({
		header: 'Our default header',
		backgroundColor: 'yellow'
	});
})();
```

Instead of this which is in the current docs
```
setGlobal({
		header: 'Our default header',
		backgroundColor: 'yellow'
	});
```

If this change is okay, I'd gladly push a pull request to the docs to make the change

**Comment by CharlesStover** [comment]
I'm not sure I understand -- what is the benefit of the former over the latter? Why should the docs list the former instead of the latter?

**Comment by gwuah** [comment]
The `setState()` fn in react is also asynchronous but you don't see people writing it in iife's.
I don't think there's a need to put the mutation function in iife.

**Comment by CharlesStover** [comment]
I think I will close this. Feel free to comment/re-open if you can provide more information.

`setGlobal`, being a Promise, is meant to support `await` syntax, but it does not have to be wrapped in an `async` IIFE. If you remove the `async` IIFE and remove the `await` keyword, you'll have the same effect with less code.
