### ISSUE TITLE
useGlobal with reducer - state is 'undefined'

### ISSUE THREAD

**Issue by slugs99** [CharlesStover/reactn#75]
Hi there,

I tried to follow the documentation per link below when calling **useGlobal** with a **reducer**. But an exception is thrown because state is 'undefined'.
 https://gist.githubusercontent.com/CharlesStover/285f95bba12cd9468276d766a87a3568/raw/c386149729ff7d17c16318563be6613baf933448/global-reducer.js

npx create-react-app my-app
cd my-app
npm i reactn && rm -rf node_modules && npm i && npm start

```
import React from "reactn";

const { setGlobal, useGlobal } = React;

setGlobal({ count: 0 });

function reducer(state, action) {
  switch (action.type) {
    case "reset":
      return { count: 0 };
    case "increment":
      return { count: state.count + 1 };
    case "decrement":
      return { count: state.count - 1 };
  }
}

function App() {
  const [state, dispatch] = useGlobal(reducer);
  const reset = () => dispatch({ type: "reset" });
  const increment = () => dispatch({ type: "increment" });
  const decrement = () => dispatch({ type: "decrement" });
  
  console.log("state value:", state); // state is 'undefined' here so calling 'state.count' throws
  
  return (
    <div>
      Count: {state.count}
      <button onClick={reset}>Reset</button>
      <button onClick={increment}>+</button>
      <button onClick={decrement}>-</button>
    </div>
  );
}

export default App;
```

**Comment by CharlesStover** [comment]
If you are using ReactN 2.0, you want to use `useDispatch(reducer)` instead of `useGlobal(reducer)`. This was a breaking change from 1.0 to 2.0.

The Medium articles I wrote reference the 1.0 documentation. Sorry for the confusion.

**Comment by slugs99** [comment]
Cool! It works!
