### ISSUE TITLE
Add CodeSandbox examples for basic use cases 

### ISSUE THREAD

**Issue by bpas247** [CharlesStover/reactn#86]
[CodeSandbox](https://codesandbox.io/) provides a way to deploy example project setups. Due to the way you can [import specific paths for GitHub repositories](https://codesandbox.io/docs/importing#import-from-github), we should consider adding examples to a new subdirectory in this repository for these examples, as it will allow users to be able to bootstrap their ReactN projects.

**Comment by CharlesStover** [comment]
I support this idea. But given I don't have a lot of experience with CodeSandbox, I'll probably prioritize finishing the documentation over this. I do welcome user-submitted CodeSandbox examples, though, and I'll leave this as a milestone for after the documentation is completed.

**Comment by pikilon** [comment]
I am trying to do examples but I get null from global state

![image](https://user-images.githubusercontent.com/3034213/63429111-794fa500-c419-11e9-98dc-493e9e41b457.png)

I can't tell if is the codesandbox or the `reactn`

https://codesandbox.io/embed/testing-reactn-hooks-lc0ci

**Comment by CharlesStover** [comment]
Looks like it should be `const [cards] = useGlobal('cards');`

As is, you are returning the entire global state object instead of the array of cards.

**Comment by pikilon** [comment]
can you access nested state with this pattern or simillar?
```const [id] = useGlobal('users.id');```
