### ISSUE TITLE
how to store an object in the global state?

### ISSUE THREAD

**Issue by rawadrifai** [CharlesStover/reactn#99]
I am not sure if I'm missing something obvious, but does this library allow to store objects in the global state? 
something like `setGlobal('key', { attr: 'val' });`

**Comment by CharlesStover** [comment]
The syntax would be `setGlobal({ key: { attr: 'val' } });`, same as if you were to store an object on a class Component's local state. Let me know if you need further assistance.

**Comment by rawadrifai** [comment]
That works @CharlesStover . Thank you!
Great library btw - I've always been discouraged by React and React Native due to redux and cumbersome state management. This library changed things for me.

**Comment by CharlesStover** [comment]
I'm very happy to hear it! 😊
